# -*- coding: utf-8 -*-
"""Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g7XniSPIVTpdud22sVYpxIUV69QGKz5S
"""

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
datos_agua = pd.read_csv(io.BytesIO(uploaded['base_de_datos_agua.csv']))

datos_agua

datos_agua.info()

datos_agua.hist()

datos_agua = datos_agua.drop(columns=['ID de Vivienda'])
datos_agua = datos_agua.drop(columns=['Ubicacion'])
datos_agua = datos_agua.drop(columns=['Fuente de agua'])
datos_agua

import matplotlib.pyplot as plt
plt.scatter(x = datos_agua['Consumo de agua abril (m³)'], y=datos_agua['Número de Habitantes'])
plt.title('Consumo de agua abril (m³) Vs Número de Habitantes')
plt.xlabel('Consumo de agua abril (m³)')
plt.ylabel('Número de Habitantes')
plt.show()

"""ENTRENAMIENTO

"""

datos_entrenamiento = datos_agua.sample(frac=0.8, random_state=0)
datos_test = datos_agua.drop(datos_entrenamiento.index)

datos_entrenamiento

etiquetas_entrenamiento = datos_entrenamiento.pop('Consumo de agua octubre (m³)')
etiquetas_test = datos_test.pop('Consumo de agua octubre (m³)')

datos_entrenamiento

datos_agua = datos_agua.drop(columns=['Tipo de vivienda'])
datos_agua = datos_agua.drop(columns=['Tipo de uso'])
datos_agua

datos_entrenamiento = datos_agua.sample(frac=0.8, random_state=0)
datos_test = datos_agua.drop(datos_entrenamiento.index)

datos_entrenamiento

etiquetas_entrenamiento = datos_entrenamiento.pop('Consumo de agua octubre (m³)')
etiquetas_test = datos_test.pop('Consumo de agua octubre (m³)')

etiquetas_entrenamiento

from sklearn.linear_model import LinearRegression
modelo = LinearRegression()
modelo.fit(datos_entrenamiento, etiquetas_entrenamiento)

predicciones= modelo.predict (datos_test)
predicciones

import numpy as np
from sklearn.metrics import mean_squared_error
error = np.sqrt(mean_squared_error(etiquetas_test, predicciones))
error_porcentual = error * 1
print("Error porcentual: %f" % error_porcentual)

nuevo_usuario = pd.DataFrame(np.array([[20, 15, 11, 14, 21, 15, 16, 11, 9, 7]]), columns=['Consumo de agua enero (m³)', 'Consumo de agua febrero (m³)', 'Consumo de agua marzo (m³)', 'Consumo de agua abril (m³)', 'Consumo de agua mayo (m³)', 'Consumo de agua junio (m³)', 'Consumo de agua julio (m³)', 'Consumo de agua agosto (m³)', 'Consumo de agua septiembre (m³)', 'Número de Habitantes'])
nuevo_usuario

modelo.predict(nuevo_usuario)